/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMdiAccessPointOff: typeof import('~icons/mdi/access-point-off')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiStopwatchPauseOutline: typeof import('~icons/mdi/stopwatch-pause-outline')['default']
  }
}


declare module 'virtual:pwa-register/vue' {
    import type { Ref } from 'vue'
    import type { RegisterSWOptions } from 'vite-plugin-pwa/types'

    export type { RegisterSWOptions }

    export function useRegisterSW(options?: RegisterSWOptions): {
        needRefresh: Ref<boolean>
        offlineReady: Ref<boolean>
        updateServiceWorker: (reloadPage?: boolean) => Promise<void>
    }
}