/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMdiAccessPointOff: typeof import('~icons/mdi/access-point-off')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiStopwatchPauseOutline: typeof import('~icons/mdi/stopwatch-pause-outline')['default']
  }
}
