# Simple workflow for deploying static content to GitHub Pages
name: Build Renderer

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: ''
          cache: 'npm'
      - run: npm install
      - run: npm run build:web
      - run: cp -rf ./build/renderer ~/
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Verteilen/.github
          ref: main
          token: ${{ secrets.PAT }}
          clean: false
      - name: Replace files
        run: |
          cp -f ~/renderer/index.html ./index.html
          cp -rf ~/renderer/assets .
      - name: Push
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: .
          destination-github-username: 'Verteilen'
          destination-repository-name: '.github'
          user-email: Elly2018@users.noreply.github.com
          commit-message: Automated update static website
          target-branch: main
